# Generated by Django 2.0.2 on 2018-03-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('till_number', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=35)),
                ('transaction_ref_no', models.CharField(max_length=20)),
                ('served_by', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
