# Generated by Django 2.0.3 on 2018-03-31 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 31, 9, 43, 50, 423091, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_ref_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('mobile_number', 'timestamp')},
        ),
    ]
